#ifndef XAIOS_CONTROL_PROTOCOL_CODES_H
#define XAIOS_CONTROL_PROTOCOL_CODES_H

/* Operation codes, payload type codes, status codes, roles, service states
   and readiness bits for the control protocol. Private sub-header of
   control_protocol.h -- include that, not this. The values are wire ABI
   and keep their exact numbering. */

typedef enum xaios_control_operation {
  XAIOS_CONTROL_OP_VERSION = 1,
  XAIOS_CONTROL_OP_STATUS = 2,
  XAIOS_CONTROL_OP_HEALTH = 3,
  XAIOS_CONTROL_OP_CAPABILITIES = 4,
  XAIOS_CONTROL_OP_HARDWARE = 5,
  XAIOS_CONTROL_OP_METRICS = 6,
  XAIOS_CONTROL_OP_LOGS = 7,
  XAIOS_CONTROL_OP_CONFIG_SHOW = 8,
  XAIOS_CONTROL_OP_CONFIG_VALIDATE = 9,
  XAIOS_CONTROL_OP_CONFIG_DIFF = 10,
  XAIOS_CONTROL_OP_CONFIG_APPLY = 11,
  XAIOS_CONTROL_OP_AUTH_KEY_LIST = 12,
  XAIOS_CONTROL_OP_AUTH_KEY_ADD = 13,
  XAIOS_CONTROL_OP_AUTH_KEY_REMOVE = 14,
  XAIOS_CONTROL_OP_AUTH_HOST_KEY_ROTATE = 15,
  XAIOS_CONTROL_OP_AUDIT_SHOW = 16,
  XAIOS_CONTROL_OP_MODEL_VERIFY = 17,
  XAIOS_CONTROL_OP_MODEL_ACTIVATE = 18,
  XAIOS_CONTROL_OP_STORAGE_DEVICE_LIST = 19,
  XAIOS_CONTROL_OP_STORAGE_DEVICE_SHOW = 20,
  XAIOS_CONTROL_OP_STORAGE_FILESYSTEM_LIST = 21,
  XAIOS_CONTROL_OP_STORAGE_FILESYSTEM_SHOW = 22,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_LIST = 23,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_VERIFY = 24,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_PLAN_CREATE = 25,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_CREATE = 26,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_PLAN_DELETE = 27,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_DELETE = 28,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_PLAN_RESIZE = 29,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_RESIZE = 30,
  XAIOS_CONTROL_OP_STORAGE_PARTITION_REPAIR = 31,
  XAIOS_CONTROL_OP_STORAGE_FORMAT_PLAN = 32,
  XAIOS_CONTROL_OP_STORAGE_FORMAT = 33,
  XAIOS_CONTROL_OP_STORAGE_MOUNT = 34,
  XAIOS_CONTROL_OP_STORAGE_UNMOUNT = 35,
  XAIOS_CONTROL_OP_STORAGE_FSCK = 36,
  XAIOS_CONTROL_OP_STORAGE_FS_REPAIR = 37,
  XAIOS_CONTROL_OP_STORAGE_FS_RESIZE_PLAN = 38,
  XAIOS_CONTROL_OP_STORAGE_FS_RESIZE = 39,
  XAIOS_CONTROL_OP_MODEL_REGISTER = 40,
  XAIOS_CONTROL_OP_STORAGE_SCRUB_START = 41,
  XAIOS_CONTROL_OP_STORAGE_SCRUB_STATUS = 42,
  XAIOS_CONTROL_OP_STORAGE_SCRUB_PAUSE = 43,
  XAIOS_CONTROL_OP_STORAGE_SCRUB_RESUME = 44,
  XAIOS_CONTROL_OP_STORAGE_SCRUB_CANCEL = 45,
  XAIOS_CONTROL_OP_STORAGE_TRIM_START = 46,
  XAIOS_CONTROL_OP_STORAGE_TRIM_STATUS = 47,
  XAIOS_CONTROL_OP_STORAGE_TRIM_CANCEL = 48,
  XAIOS_CONTROL_OP_MODEL_CLEANUP = 49,
  XAIOS_CONTROL_OP_APP_ACTIVATE = 50,
  XAIOS_CONTROL_OP_APP_REMOVE = 51,
  XAIOS_CONTROL_OP_APP_ROLLBACK = 52,
  XAIOS_CONTROL_OP_CATALOG_ACTIVATE = 53,
  XAIOS_CONTROL_OP_SYSTEM_UPDATE_BEGIN = 54,
  XAIOS_CONTROL_OP_SYSTEM_UPDATE_CHUNK = 55,
  XAIOS_CONTROL_OP_SYSTEM_UPDATE_COMMIT = 56,
  XAIOS_CONTROL_OP_SYSTEM_UPDATE_ABORT = 57,
  XAIOS_CONTROL_OP_RUNTIME_SNAPSHOT = 58,
  XAIOS_CONTROL_OP_STORAGE_REPAIR_FROM_REPLICA = 59,
  /* Partition a disk, format its EFI System Partition and copy this machine's
     own boot files onto it. Destroys whatever the target held, so it carries
     the same confirmation, actor and audit requirements as the partition
     mutations above. */
  XAIOS_CONTROL_OP_STORAGE_INSTALL = 60,
} xaios_control_operation_t;

typedef enum xaios_control_payload_type {
  XAIOS_CONTROL_PAYLOAD_NONE = 0,
  XAIOS_CONTROL_PAYLOAD_VERSION = 1,
  XAIOS_CONTROL_PAYLOAD_STATUS = 2,
  XAIOS_CONTROL_PAYLOAD_HEALTH = 3,
  XAIOS_CONTROL_PAYLOAD_CAPABILITIES = 4,
  XAIOS_CONTROL_PAYLOAD_HARDWARE = 5,
  XAIOS_CONTROL_PAYLOAD_METRICS = 6,
  XAIOS_CONTROL_PAYLOAD_LOG_REQUEST = 7,
  XAIOS_CONTROL_PAYLOAD_LOGS = 8,
  XAIOS_CONTROL_PAYLOAD_PATH_REQUEST = 9,
  XAIOS_CONTROL_PAYLOAD_MUTATION_REQUEST = 10,
  XAIOS_CONTROL_PAYLOAD_AUDIT_REQUEST = 11,
  XAIOS_CONTROL_PAYLOAD_CONFIG = 12,
  XAIOS_CONTROL_PAYLOAD_AUTH_KEYS = 13,
  XAIOS_CONTROL_PAYLOAD_MUTATION = 14,
  XAIOS_CONTROL_PAYLOAD_AUDIT = 15,
  XAIOS_CONTROL_PAYLOAD_STORAGE_DEVICES = 16,
  XAIOS_CONTROL_PAYLOAD_STORAGE_FILESYSTEMS = 17,
  XAIOS_CONTROL_PAYLOAD_STORAGE_PARTITION_REQUEST = 18,
  XAIOS_CONTROL_PAYLOAD_STORAGE_PARTITIONS = 19,
  XAIOS_CONTROL_PAYLOAD_STORAGE_PARTITION_PLAN = 20,
  XAIOS_CONTROL_PAYLOAD_STORAGE_VOLUME_REQUEST = 21,
  XAIOS_CONTROL_PAYLOAD_STORAGE_VOLUME_REPORT = 22,
  XAIOS_CONTROL_PAYLOAD_MODEL_REGISTER_REQUEST = 23,
  XAIOS_CONTROL_PAYLOAD_STORAGE_SCRUB_REPORT = 24,
  XAIOS_CONTROL_PAYLOAD_STORAGE_TRIM_REQUEST = 25,
  XAIOS_CONTROL_PAYLOAD_STORAGE_TRIM_REPORT = 26,
  XAIOS_CONTROL_PAYLOAD_MODEL_CLEANUP_REPORT = 27,
  XAIOS_CONTROL_PAYLOAD_APP_REQUEST = 28,
  XAIOS_CONTROL_PAYLOAD_SYSTEM_UPDATE_BEGIN = 29,
  XAIOS_CONTROL_PAYLOAD_SYSTEM_UPDATE_CHUNK = 30,
  XAIOS_CONTROL_PAYLOAD_RUNTIME_SNAPSHOT_REQUEST = 31,
  XAIOS_CONTROL_PAYLOAD_RUNTIME_SNAPSHOT = 32,
  XAIOS_CONTROL_PAYLOAD_STORAGE_REPLICA_REPAIR_REQUEST = 33,
  XAIOS_CONTROL_PAYLOAD_STORAGE_INSTALL_REQUEST = 34,
  XAIOS_CONTROL_PAYLOAD_STORAGE_INSTALL_RESULT = 35,
} xaios_control_payload_type_t;

typedef enum xaios_control_status {
  XAIOS_CONTROL_STATUS_OK = 0,
  XAIOS_CONTROL_STATUS_INVALID_REQUEST = 1,
  XAIOS_CONTROL_STATUS_UNSUPPORTED_VERSION = 2,
  XAIOS_CONTROL_STATUS_UNKNOWN_OPERATION = 3,
  XAIOS_CONTROL_STATUS_DENIED = 4,
  XAIOS_CONTROL_STATUS_BUFFER_TOO_SMALL = 5,
  XAIOS_CONTROL_STATUS_TIMEOUT = 6,
  XAIOS_CONTROL_STATUS_INTERNAL = 7,
  XAIOS_CONTROL_STATUS_UNKNOWN_NODE = 8,
  XAIOS_CONTROL_STATUS_NOT_FOUND = 9,
  XAIOS_CONTROL_STATUS_REPLAYED = 10,
  XAIOS_CONTROL_STATUS_CONFLICT = 11,
} xaios_control_status_t;

typedef enum xaios_control_role {
  XAIOS_CONTROL_ROLE_NONE = 0,
  XAIOS_CONTROL_ROLE_OBSERVER = 1,
  XAIOS_CONTROL_ROLE_OPERATOR = 2,
  XAIOS_CONTROL_ROLE_ADMIN = 3,
} xaios_control_role_t;

typedef enum xaios_control_state {
  XAIOS_CONTROL_STATE_UNKNOWN = 0,
  XAIOS_CONTROL_STATE_STOPPED = 1,
  XAIOS_CONTROL_STATE_RUNNING = 2,
  XAIOS_CONTROL_STATE_READY = 3,
  XAIOS_CONTROL_STATE_DEGRADED = 4,
  XAIOS_CONTROL_STATE_FATAL = 5,
  XAIOS_CONTROL_STATE_UNSUPPORTED = 6,
  XAIOS_CONTROL_STATE_INTERFACE_ONLY = 7,
  XAIOS_CONTROL_STATE_FIXTURE_ONLY = 8,
  XAIOS_CONTROL_STATE_AVAILABLE = 9,
} xaios_control_state_t;

#define XAIOS_CONTROL_READINESS_SSH UINT64_C(1)
#define XAIOS_CONTROL_READINESS_NETWORK UINT64_C(2)
#define XAIOS_CONTROL_READINESS_STORAGE UINT64_C(4)
#define XAIOS_CONTROL_READINESS_MODEL UINT64_C(8)
#define XAIOS_CONTROL_READINESS_INFERENCE UINT64_C(16)
#define XAIOS_CONTROL_READINESS_CLUSTER UINT64_C(32)

#endif
