#!/usr/bin/env python3
"""Keep source files from growing past the size the repository allows.

This is a ratchet, not a cleanup. XAIOS has 119 tracked source files over 500
lines, 44 of them over 1000, and the largest -- `kernel/runtime/network_stack.c`
-- is nearly 5900. Splitting them is real work with real risk: these are a
working kernel's state machines, not text. What this check does instead is make
the debt visible and stop it growing, which is the part that can be done
mechanically:

  - a file at or under `LIMIT` lines is fine;
  - a file over it is allowed only if `file-size-budget.txt` names it and it has
    not grown since the baseline was recorded;
  - a baseline entry that has come back under the limit is reported so it can be
    dropped, and `--update` rewrites the file after a split.

So a new 600-line file fails, an existing 5900-line file fails if it becomes
5901, and a split that takes one from 1200 to 400 is a line to delete rather
than a rewrite of anything. The counting is what a reviewer would count:
physical lines of tracked code, with vendored trees and generated data excluded.

Usage:
    python3 tests/repository/check-file-size-budget.py [--update]

`--update` records the current sizes as the new baseline. It never raises an
existing entry's allowance silently for a reason other than growth that has
already happened -- run it when a split lands, and read the diff.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE = ROOT / "tests" / "repository" / "file-size-budget.txt"

# The rule the repository states. A file over this has to be in the baseline.
LIMIT = 500

# Code, not data: these are the extensions a reviewer reads as source, plus the
# Makefile, which is the single largest hand-written file in the tree.
SUFFIXES = (".c", ".h", ".py", ".sh", ".S", ".ld", ".mk")
EXTRA_NAMES = ("Makefile",)

# Vendored upstream code is not this repository's to split, and the test
# fixtures are generated byte arrays rather than logic.
EXCLUDED_PREFIXES = ("third_party/", "build/", "release/")


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                         text=True, check=True).stdout.split()
    keep = []
    for name in out:
        if name.startswith(EXCLUDED_PREFIXES):
            continue
        if not (name.endswith(SUFFIXES) or Path(name).name in EXTRA_NAMES):
            continue
        if Path(name).name.startswith("wt_") and name.endswith("_vectors.h"):
            continue
        keep.append(name)
    return keep


def count_lines(name: str) -> int:
    try:
        with (ROOT / name).open("rb") as handle:
            return sum(1 for _ in handle)
    except OSError:
        return 0


def read_baseline() -> dict[str, int]:
    entries: dict[str, int] = {}
    if not BASELINE.exists():
        return entries
    for line in BASELINE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 2 or not parts[1].isdigit():
            print(f"file-size-budget: malformed baseline line: {line}",
                  file=sys.stderr)
            raise SystemExit(2)
        entries[parts[0]] = int(parts[1])
    return entries


def write_baseline(sizes: dict[str, int]) -> None:
    lines = [
        "# Files over the 500-line limit, with the size they are allowed to be.",
        "# Generated by check-file-size-budget.py --update. A split lowers a",
        "# number or removes a line; nothing here may grow.",
        "",
    ]
    for name in sorted(sizes):
        lines.append(f"{name} {sizes[name]}")
    BASELINE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true",
                        help="record the current sizes as the baseline")
    args = parser.parse_args()

    oversized = {name: count_lines(name) for name in tracked_files()}
    oversized = {name: size for name, size in oversized.items() if size > LIMIT}

    if args.update:
        write_baseline(oversized)
        print(f"file-size-budget: baseline recorded, {len(oversized)} files over "
              f"{LIMIT} lines")
        return 0

    baseline = read_baseline()
    grown = sorted((name, size, baseline[name]) for name, size in oversized.items()
                   if name in baseline and size > baseline[name])
    new = sorted((name, size) for name, size in oversized.items()
                 if name not in baseline)
    back_under = sorted(name for name in baseline
                        if name not in oversized)

    for name, size, allowed in grown:
        print(f"file-size-budget: {name} grew from {allowed} to {size} lines",
              file=sys.stderr)
    for name, size in new:
        print(f"file-size-budget: {name} is {size} lines and is not in the "
              f"baseline (limit {LIMIT})", file=sys.stderr)
    if grown or new:
        print("file-size-budget: split the file, or lower the baseline with "
              "--update only when a size has gone down", file=sys.stderr)
        return 1

    if back_under:
        print("file-size-budget: these are back under the limit and can be "
              "deleted from file-size-budget.txt:")
        for name in back_under:
            print(f"  {name}")
        return 1

    print(f"file-size-budget: {len(oversized)} files over {LIMIT} lines, none "
          f"grown, and no new one")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
