# Sourced by scripts/build-image.sh; not a standalone script.
#
# Compiles every kernel translation unit, writes the linker response file
# and links $KERNEL_ELF. Runs in the caller's shell, so it uses the
# compile_kernel functions and the KERNEL_CFLAGS/KERNEL_OBJECTS defined
# just before it.

if [ "$TARGET_ARCH" = aarch64 ]; then
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/entry.S" "$KERNEL_BUILD_DIR/entry.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/secondary.S" "$KERNEL_BUILD_DIR/secondary.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/vectors.S" "$KERNEL_BUILD_DIR/vectors.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/acpi.c" "$KERNEL_BUILD_DIR/acpi.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/cpu_features.c" "$KERNEL_BUILD_DIR/cpu_features.o"
else
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/entry.S" "$KERNEL_BUILD_DIR/entry.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/acpi.c" "$KERNEL_BUILD_DIR/acpi.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/cpu_features.c" "$KERNEL_BUILD_DIR/cpu_features.o"
fi
compile_kernel "$ROOT_DIR/kernel/core/kmain.c" "$KERNEL_BUILD_DIR/kmain.o"
compile_kernel "$ROOT_DIR/kernel/core/boot_storage.c" "$KERNEL_BUILD_DIR/boot_storage.o"
compile_kernel "$ROOT_DIR/kernel/core/boot_apps.c" "$KERNEL_BUILD_DIR/boot_apps.o"
compile_kernel "$ROOT_DIR/kernel/core/boot_ui.c" "$KERNEL_BUILD_DIR/boot_ui.o"
compile_kernel "$ROOT_DIR/kernel/core/boot_ui_render.c" "$KERNEL_BUILD_DIR/boot_ui_render.o"
compile_kernel "$ROOT_DIR/kernel/core/boot_ui_term.c" "$KERNEL_BUILD_DIR/boot_ui_term.o"
compile_kernel "$ROOT_DIR/kernel/core/klog.c" "$KERNEL_BUILD_DIR/klog.o"
compile_kernel "$ROOT_DIR/kernel/core/idle_wake.c" "$KERNEL_BUILD_DIR/idle_wake.o"
compile_kernel "$ROOT_DIR/kernel/dev/input.c" "$KERNEL_BUILD_DIR/input.o"
compile_kernel "$ROOT_DIR/kernel/core/klog_ring.c" "$KERNEL_BUILD_DIR/klog_ring.o"
compile_kernel "$ROOT_DIR/kernel/core/telemetry.c" "$KERNEL_BUILD_DIR/telemetry.o"
compile_kernel "$ROOT_DIR/kernel/core/panic.c" "$KERNEL_BUILD_DIR/panic.o"
compile_kernel "$ROOT_DIR/kernel/core/assert.c" "$KERNEL_BUILD_DIR/assert.o"
compile_kernel "$ROOT_DIR/kernel/core/stack_canary.c" "$KERNEL_BUILD_DIR/stack_canary.o"
if [ "$TARGET_ARCH" = aarch64 ]; then
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/exception.c" "$KERNEL_BUILD_DIR/exception.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/timer.c" "$KERNEL_BUILD_DIR/timer.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/rtc.c" "$KERNEL_BUILD_DIR/rtc.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/power.c" "$KERNEL_BUILD_DIR/power.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/watchdog.c" "$KERNEL_BUILD_DIR/watchdog.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/smmu.c" "$KERNEL_BUILD_DIR/smmu.o"
  compile_kernel "$ROOT_DIR/kernel/dev/pci_ecam.c" "$KERNEL_BUILD_DIR/pci.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/gic.c" "$KERNEL_BUILD_DIR/gic.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/gic_its.c" "$KERNEL_BUILD_DIR/gic_its.o"
  compile_kernel "$ROOT_DIR/kernel/arch/aarch64/smp.c" "$KERNEL_BUILD_DIR/smp.o"
compile_kernel "$ROOT_DIR/kernel/arch/aarch64/mmu_boot.c" "$KERNEL_BUILD_DIR/mmu_boot.o"
compile_kernel "$ROOT_DIR/kernel/arch/aarch64/mmu_user.c" "$KERNEL_BUILD_DIR/mmu_user.o"
  # The packed engine, which until now was compiled for x86_64 only. The
  # AArch64 kernel could not reach a packed kernel of any kind, so the NEON
  # path in it had never been linked into a running system on this
  # architecture -- and the SVE path could not have been.
  compile_kernel_simd "$ROOT_DIR/engine/src/packed.c" "$KERNEL_BUILD_DIR/engine_packed.o"
  compile_kernel_simd "$ROOT_DIR/kernel/arch/aarch64/sve.c" "$KERNEL_BUILD_DIR/sve.o"
  compile_kernel_simd "$ROOT_DIR/kernel/arch/aarch64/sve_canary.S" "$KERNEL_BUILD_DIR/sve_canary.o"
else
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early.c" "$KERNEL_BUILD_DIR/early.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_tlb.c" "$KERNEL_BUILD_DIR/early_tlb.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_cpu.c" "$KERNEL_BUILD_DIR/early_cpu.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_mem.c" "$KERNEL_BUILD_DIR/early_mem.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_pci.c" "$KERNEL_BUILD_DIR/early_pci.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_serial.c" "$KERNEL_BUILD_DIR/early_serial.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_acpi.c" "$KERNEL_BUILD_DIR/early_acpi.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_fpu.c" "$KERNEL_BUILD_DIR/early_fpu.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_irq.c" "$KERNEL_BUILD_DIR/early_irq.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_gdt.c" "$KERNEL_BUILD_DIR/early_gdt.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_platform.c" "$KERNEL_BUILD_DIR/early_platform.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_timer_discover.c" "$KERNEL_BUILD_DIR/early_timer_discover.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_exception.c" "$KERNEL_BUILD_DIR/early_exception.o"
compile_kernel "$ROOT_DIR/kernel/arch/x86_64/early_contract.c" "$KERNEL_BUILD_DIR/early_contract.o"
  compile_kernel_simd "$ROOT_DIR/engine/src/packed.c" "$KERNEL_BUILD_DIR/engine_packed.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/timer.c" "$KERNEL_BUILD_DIR/timer.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/platform.c" "$KERNEL_BUILD_DIR/platform.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/power.c" "$KERNEL_BUILD_DIR/power.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/watchdog.c" "$KERNEL_BUILD_DIR/watchdog.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/pci.c" "$KERNEL_BUILD_DIR/pci.o"
  compile_kernel "$ROOT_DIR/kernel/arch/x86_64/smp.c" "$KERNEL_BUILD_DIR/smp.o"
fi
compile_kernel "$ROOT_DIR/kernel/arch/aarch64/topology.c" "$KERNEL_BUILD_DIR/topology.o"
compile_kernel "$ROOT_DIR/kernel/dev/nvme.c" "$KERNEL_BUILD_DIR/nvme.o"
compile_kernel "$ROOT_DIR/kernel/dev/nvme_queue.c" "$KERNEL_BUILD_DIR/nvme_queue.o"
compile_kernel "$ROOT_DIR/kernel/dev/nvme_completion.c" "$KERNEL_BUILD_DIR/nvme_completion.o"
compile_kernel "$ROOT_DIR/kernel/dev/nvme_admin.c" "$KERNEL_BUILD_DIR/nvme_admin.o"
compile_kernel "$ROOT_DIR/kernel/dev/nvme_selftest.c" "$KERNEL_BUILD_DIR/nvme_selftest.o"
compile_kernel "$ROOT_DIR/kernel/dev/ahci.c" "$KERNEL_BUILD_DIR/ahci.o"
if [ "$TARGET_ARCH" = aarch64 ]; then
  # aarch64 can meet virtio on either transport, so both are built and a
  # dispatcher picks between them. x86_64 only ever sees PCI.
  compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_transport.c" \
    "$KERNEL_BUILD_DIR/virtio_transport_mmio.o" "-DXAIOS_VIRTIO_MMIO_BACKEND=1"
  compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_transport_pci.c" \
    "$KERNEL_BUILD_DIR/virtio_transport_pci.o" "-DXAIOS_VIRTIO_PCI_BACKEND=1"
  compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_transport_dispatch.c" \
    "$KERNEL_BUILD_DIR/virtio_transport.o"
else
  compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_transport_pci.c" "$KERNEL_BUILD_DIR/virtio_transport.o"
fi
compile_kernel "$ROOT_DIR/kernel/dev/block_device.c" "$KERNEL_BUILD_DIR/block_device.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_blk.c" "$KERNEL_BUILD_DIR/virtio_blk.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_blk_handles.c" "$KERNEL_BUILD_DIR/virtio_blk_handles.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_blk_request.c" "$KERNEL_BUILD_DIR/virtio_blk_request.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_blk_backend.c" "$KERNEL_BUILD_DIR/virtio_blk_backend.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_net.c" "$KERNEL_BUILD_DIR/virtio_net.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_net_selftest.c" "$KERNEL_BUILD_DIR/virtio_net_selftest.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_net_tx.c" "$KERNEL_BUILD_DIR/virtio_net_tx.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_net_setup.c" "$KERNEL_BUILD_DIR/virtio_net_setup.o"
compile_kernel "$ROOT_DIR/kernel/dev/e1000e.c" "$KERNEL_BUILD_DIR/e1000e.o"
compile_kernel "$ROOT_DIR/kernel/dev/vmxnet3.c" "$KERNEL_BUILD_DIR/vmxnet3.o"
compile_kernel "$ROOT_DIR/kernel/dev/vmxnet3_rings.c" "$KERNEL_BUILD_DIR/vmxnet3_rings.o"
compile_kernel "$ROOT_DIR/kernel/dev/vmxnet3_data.c" "$KERNEL_BUILD_DIR/vmxnet3_data.o"
compile_kernel "$ROOT_DIR/kernel/dev/net_device.c" "$KERNEL_BUILD_DIR/net_device.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_rng.c" "$KERNEL_BUILD_DIR/virtio_rng.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_gpu.c" "$KERNEL_BUILD_DIR/virtio_gpu.o"
compile_kernel "$ROOT_DIR/kernel/dev/virtio/virtio_console.c" "$KERNEL_BUILD_DIR/virtio_console.o"
compile_kernel "$ROOT_DIR/kernel/runtime/arch_random.c" "$KERNEL_BUILD_DIR/arch_random.o"
compile_kernel "$ROOT_DIR/kernel/runtime/entropy.c" "$KERNEL_BUILD_DIR/entropy.o"
compile_kernel "$ROOT_DIR/kernel/sched/smp_task_set.c" "$KERNEL_BUILD_DIR/smp_task_set.o"
compile_kernel "$ROOT_DIR/kernel/fs/initramfs.c" "$KERNEL_BUILD_DIR/initramfs.o"
compile_kernel "$ROOT_DIR/kernel/fs/xaiboot_fs.c" "$KERNEL_BUILD_DIR/xaiboot_fs.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_state.c" "$KERNEL_BUILD_DIR/xbfs_state.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_node_codec.c" "$KERNEL_BUILD_DIR/xbfs_node_codec.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_util.c" "$KERNEL_BUILD_DIR/xbfs_util.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_record.c" "$KERNEL_BUILD_DIR/xbfs_record.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_metadata.c" "$KERNEL_BUILD_DIR/xbfs_metadata.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_dir.c" "$KERNEL_BUILD_DIR/xbfs_dir.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_alloc.c" "$KERNEL_BUILD_DIR/xbfs_alloc.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_file_io.c" "$KERNEL_BUILD_DIR/xbfs_file_io.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_fd.c" "$KERNEL_BUILD_DIR/xbfs_fd.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_mount.c" "$KERNEL_BUILD_DIR/xbfs_mount.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_snapshot.c" "$KERNEL_BUILD_DIR/xbfs_snapshot.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_format.c" "$KERNEL_BUILD_DIR/xbfs_format.o"
compile_kernel "$ROOT_DIR/kernel/fs/xbfs_selfcheck.c" "$KERNEL_BUILD_DIR/xbfs_selfcheck.o"
compile_kernel "$ROOT_DIR/kernel/fs/fat.c" "$KERNEL_BUILD_DIR/fat.o"
compile_kernel "$ROOT_DIR/kernel/fs/fat_codec.c" "$KERNEL_BUILD_DIR/fat_codec.o"
compile_kernel "$ROOT_DIR/kernel/fs/fat_dir.c" "$KERNEL_BUILD_DIR/fat_dir.o"
compile_kernel "$ROOT_DIR/kernel/fs/fat_file_io.c" "$KERNEL_BUILD_DIR/fat_file_io.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs.c" "$KERNEL_BUILD_DIR/vfs.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_xaiboot.c" "$KERNEL_BUILD_DIR/vfs_xaiboot.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_initramfs.c" "$KERNEL_BUILD_DIR/vfs_initramfs.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_xaifs.c" "$KERNEL_BUILD_DIR/vfs_xaifs.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_xaifs_trim.c" "$KERNEL_BUILD_DIR/vfs_xaifs_trim.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_xaifs_scrub.c" "$KERNEL_BUILD_DIR/vfs_xaifs_scrub.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_xaifs_io.c" "$KERNEL_BUILD_DIR/vfs_xaifs_io.o"
compile_kernel "$ROOT_DIR/kernel/fs/vfs_xaifs_catalog.c" "$KERNEL_BUILD_DIR/vfs_xaifs_catalog.o"
compile_kernel "$ROOT_DIR/kernel/fs/model_cache.c" "$KERNEL_BUILD_DIR/model_cache.o"
compile_kernel "$ROOT_DIR/kernel/mm/ram_residency.c" "$KERNEL_BUILD_DIR/ram_residency.o"
compile_kernel "$ROOT_DIR/kernel/dev/ram_block.c" "$KERNEL_BUILD_DIR/ram_block.o"
compile_kernel "$ROOT_DIR/kernel/runtime/setup_apply.c" "$KERNEL_BUILD_DIR/setup_apply.o"
compile_kernel "$ROOT_DIR/kernel/fs/xai_fs_admin.c" "$KERNEL_BUILD_DIR/xai_fs_admin.o"
compile_kernel "$ROOT_DIR/kernel/user/service.c" "$KERNEL_BUILD_DIR/service.o"
compile_kernel "$ROOT_DIR/kernel/user/service_registry.c" "$KERNEL_BUILD_DIR/service_registry.o"
compile_kernel "$ROOT_DIR/kernel/user/service_lifecycle.c" "$KERNEL_BUILD_DIR/service_lifecycle.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall.c" "$KERNEL_BUILD_DIR/syscall.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_table.c" "$KERNEL_BUILD_DIR/syscall_table.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_socket.c" "$KERNEL_BUILD_DIR/syscall_socket.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_file.c" "$KERNEL_BUILD_DIR/syscall_file.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_process.c" "$KERNEL_BUILD_DIR/syscall_process.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_compute.c" "$KERNEL_BUILD_DIR/syscall_compute.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_time.c" "$KERNEL_BUILD_DIR/syscall_time.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_net.c" "$KERNEL_BUILD_DIR/syscall_net.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_netio.c" "$KERNEL_BUILD_DIR/syscall_netio.o"
compile_kernel "$ROOT_DIR/kernel/user/syscall_control.c" "$KERNEL_BUILD_DIR/syscall_control.o"
compile_kernel "$ROOT_DIR/kernel/runtime/core_lease.c" "$KERNEL_BUILD_DIR/core_lease.o"
compile_kernel "$ROOT_DIR/kernel/runtime/security.c" "$KERNEL_BUILD_DIR/security.o"
compile_kernel "$ROOT_DIR/kernel/runtime/child_channel.c" "$KERNEL_BUILD_DIR/child_channel.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login.c" "$KERNEL_BUILD_DIR/remote_login.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_archive.c" "$KERNEL_BUILD_DIR/remote_login_archive.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_text.c" "$KERNEL_BUILD_DIR/remote_login_text.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_path.c" "$KERNEL_BUILD_DIR/remote_login_path.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_sysinfo.c" "$KERNEL_BUILD_DIR/remote_login_sysinfo.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_tar.c" "$KERNEL_BUILD_DIR/remote_login_tar.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_zip.c" "$KERNEL_BUILD_DIR/remote_login_zip.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_exec.c" "$KERNEL_BUILD_DIR/remote_login_exec.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_copy.c" "$KERNEL_BUILD_DIR/remote_login_copy.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_apps.c" "$KERNEL_BUILD_DIR/remote_login_apps.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_session.c" "$KERNEL_BUILD_DIR/remote_login_session.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_archive_format.c" "$KERNEL_BUILD_DIR/remote_login_archive_format.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_meta.c" "$KERNEL_BUILD_DIR/remote_login_meta.o"
compile_kernel "$ROOT_DIR/kernel/runtime/remote_login_parse.c" "$KERNEL_BUILD_DIR/remote_login_parse.o"
compile_kernel "$ROOT_DIR/kernel/runtime/operations.c" "$KERNEL_BUILD_DIR/operations.o"
compile_kernel "$ROOT_DIR/kernel/runtime/admin_control.c" "$KERNEL_BUILD_DIR/admin_control.o"
compile_kernel "$ROOT_DIR/kernel/runtime/admin_control_config.c" "$KERNEL_BUILD_DIR/admin_control_config.o"
compile_kernel "$ROOT_DIR/kernel/runtime/admin_control_auth.c" "$KERNEL_BUILD_DIR/admin_control_auth.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_protocol.c" "$KERNEL_BUILD_DIR/control_protocol.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_model_ops.c" "$KERNEL_BUILD_DIR/control_model_ops.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_report_ops.c" "$KERNEL_BUILD_DIR/control_report_ops.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_storage_ops.c" "$KERNEL_BUILD_DIR/control_storage_ops.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_ops.c" "$KERNEL_BUILD_DIR/control_ops.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_observability_ops.c" "$KERNEL_BUILD_DIR/control_observability_ops.o"
compile_kernel "$ROOT_DIR/kernel/runtime/control_storage_layout_ops.c" "$KERNEL_BUILD_DIR/control_storage_layout_ops.o"
compile_kernel "$ROOT_DIR/kernel/runtime/app_store.c" "$KERNEL_BUILD_DIR/app_store.o"
compile_kernel "$ROOT_DIR/kernel/runtime/app_store_codec.c" "$KERNEL_BUILD_DIR/app_store_codec.o"
compile_kernel "$ROOT_DIR/kernel/runtime/app_store_trust.c" "$KERNEL_BUILD_DIR/app_store_trust.o"
compile_kernel "$ROOT_DIR/kernel/user/user.c" "$KERNEL_BUILD_DIR/user.o"
compile_kernel "$ROOT_DIR/kernel/user/user_process.c" "$KERNEL_BUILD_DIR/user_process.o"
compile_kernel "$ROOT_DIR/kernel/user/user_runtime.c" "$KERNEL_BUILD_DIR/user_runtime.o"
compile_kernel "$ROOT_DIR/kernel/runtime/model_arena.c" "$KERNEL_BUILD_DIR/model_arena.o"
compile_kernel "$ROOT_DIR/kernel/runtime/ai_cell.c" "$KERNEL_BUILD_DIR/ai_cell.o"
compile_kernel "$ROOT_DIR/kernel/runtime/cpu_ai_runtime.c" "$KERNEL_BUILD_DIR/cpu_ai_runtime.o"
compile_kernel "$ROOT_DIR/kernel/runtime/cpu_ai_manifest.c" "$KERNEL_BUILD_DIR/cpu_ai_manifest.o"
compile_kernel "$ROOT_DIR/kernel/runtime/cpu_ai_fixture.c" "$KERNEL_BUILD_DIR/cpu_ai_fixture.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/ai_kernels.c" "$KERNEL_BUILD_DIR/ai_kernels.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/ai_kernels_quant.c" "$KERNEL_BUILD_DIR/ai_kernels_quant.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/ai_kernels_matmul.c" "$KERNEL_BUILD_DIR/ai_kernels_matmul.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/paged_kv_cache.c" "$KERNEL_BUILD_DIR/paged_kv_cache.o"
compile_kernel "$ROOT_DIR/kernel/runtime/inference_batcher.c" "$KERNEL_BUILD_DIR/inference_batcher.o"
compile_kernel "$ROOT_DIR/kernel/runtime/inference_preempt.c" "$KERNEL_BUILD_DIR/inference_preempt.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/model_parallel.c" "$KERNEL_BUILD_DIR/model_parallel.o"
compile_kernel "$ROOT_DIR/kernel/runtime/speculative_decoding.c" "$KERNEL_BUILD_DIR/speculative_decoding.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/flash_attention.c" "$KERNEL_BUILD_DIR/flash_attention.o"
compile_kernel "$ROOT_DIR/kernel/runtime/model_compilation.c" "$KERNEL_BUILD_DIR/model_compilation.o"
compile_kernel_simd "$ROOT_DIR/kernel/runtime/math_intrinsics.c" "$KERNEL_BUILD_DIR/math_intrinsics.o"
compile_kernel "$ROOT_DIR/kernel/runtime/sandbox.c" "$KERNEL_BUILD_DIR/sandbox.o"
compile_kernel "$ROOT_DIR/kernel/runtime/persistence.c" "$KERNEL_BUILD_DIR/persistence.o"
compile_kernel "$ROOT_DIR/kernel/runtime/update.c" "$KERNEL_BUILD_DIR/update.o"
compile_kernel "$ROOT_DIR/kernel/runtime/system_slot.c" "$KERNEL_BUILD_DIR/system_slot.o"
compile_kernel "$ROOT_DIR/kernel/runtime/sha256.c" "$KERNEL_BUILD_DIR/sha256.o"
compile_kernel "$ROOT_DIR/kernel/lib/crc32.c" "$KERNEL_BUILD_DIR/crc32.o"
compile_kernel "$ROOT_DIR/kernel/lib/inflate.c" "$KERNEL_BUILD_DIR/inflate.o"
compile_kernel "$ROOT_DIR/kernel/storage/gpt.c" "$KERNEL_BUILD_DIR/gpt.o"
compile_kernel "$ROOT_DIR/kernel/storage/partition_device.c" "$KERNEL_BUILD_DIR/partition_device.o"
compile_kernel "$ROOT_DIR/kernel/storage/storage_admin.c" "$KERNEL_BUILD_DIR/storage_admin.o"
compile_kernel "$ROOT_DIR/kernel/storage/storage_admin_table.c" "$KERNEL_BUILD_DIR/storage_admin_table.o"
compile_kernel "$ROOT_DIR/kernel/storage/storage_admin_self_test.c" "$KERNEL_BUILD_DIR/storage_admin_self_test.o"
compile_kernel "$ROOT_DIR/kernel/storage/install.c" "$KERNEL_BUILD_DIR/install.o"
compile_kernel "$ROOT_DIR/kernel/storage/storage_bench.c" "$KERNEL_BUILD_DIR/storage_bench.o"
compile_kernel "$ROOT_DIR/kernel/storage/crash_writer.c" "$KERNEL_BUILD_DIR/crash_writer.o"
compile_kernel "$ROOT_DIR/kernel/runtime/rate_limit.c" "$KERNEL_BUILD_DIR/rate_limit.o"
compile_kernel "$ROOT_DIR/kernel/runtime/source_index.c" "$KERNEL_BUILD_DIR/source_index.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack.c" "$KERNEL_BUILD_DIR/network_stack.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_wire.c" "$KERNEL_BUILD_DIR/network_stack_wire.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_listener.c" "$KERNEL_BUILD_DIR/network_stack_listener.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_v6.c" "$KERNEL_BUILD_DIR/network_stack_v6.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_flow.c" "$KERNEL_BUILD_DIR/network_stack_tcp_flow.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_segment.c" "$KERNEL_BUILD_DIR/network_stack_tcp_segment.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_packet.c" "$KERNEL_BUILD_DIR/network_stack_packet.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_udp.c" "$KERNEL_BUILD_DIR/network_stack_udp.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_udp_rx.c" "$KERNEL_BUILD_DIR/network_stack_udp_rx.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_icmp.c" "$KERNEL_BUILD_DIR/network_stack_icmp.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_poll.c" "$KERNEL_BUILD_DIR/network_stack_poll.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_local.c" "$KERNEL_BUILD_DIR/network_stack_local.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_app.c" "$KERNEL_BUILD_DIR/network_stack_app.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_selftest.c" "$KERNEL_BUILD_DIR/network_stack_selftest.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_stats.c" "$KERNEL_BUILD_DIR/network_stack_tcp_stats.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_lifecycle.c" "$KERNEL_BUILD_DIR/network_stack_lifecycle.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_table.c" "$KERNEL_BUILD_DIR/network_stack_tcp_table.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_timers.c" "$KERNEL_BUILD_DIR/network_stack_tcp_timers.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_drain.c" "$KERNEL_BUILD_DIR/network_stack_tcp_drain.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_api.c" "$KERNEL_BUILD_DIR/network_stack_tcp_api.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_frame.c" "$KERNEL_BUILD_DIR/network_stack_tcp_frame.o"
compile_kernel "$ROOT_DIR/kernel/runtime/network_stack_tcp_frame_v6.c" "$KERNEL_BUILD_DIR/network_stack_tcp_frame_v6.o"
compile_kernel "$ROOT_DIR/kernel/net/network_config.c" "$KERNEL_BUILD_DIR/network_config.o"
compile_kernel "$ROOT_DIR/kernel/runtime/git_workspace.c" "$KERNEL_BUILD_DIR/git_workspace.o"
compile_kernel "$ROOT_DIR/kernel/runtime/agent_protocol.c" "$KERNEL_BUILD_DIR/agent_protocol.o"
compile_kernel "$ROOT_DIR/kernel/mm/pmm.c" "$KERNEL_BUILD_DIR/pmm.o"
compile_kernel "$ROOT_DIR/kernel/mm/numa.c" "$KERNEL_BUILD_DIR/numa.o"
compile_kernel "$ROOT_DIR/kernel/mm/numa_topology.c" "$KERNEL_BUILD_DIR/numa_topology.o"
compile_kernel "$ROOT_DIR/kernel/mm/numa_selftest.c" "$KERNEL_BUILD_DIR/numa_selftest.o"
compile_kernel "$ROOT_DIR/kernel/mm/arena.c" "$KERNEL_BUILD_DIR/arena.o"
compile_kernel "$ROOT_DIR/kernel/mm/kheap.c" "$KERNEL_BUILD_DIR/kheap.o"
compile_kernel "$ROOT_DIR/kernel/mm/device_window.c" "$KERNEL_BUILD_DIR/device_window.o"
compile_kernel "$ROOT_DIR/kernel/arch/$ARCH_KERNEL_DIR/mmu.c" "$KERNEL_BUILD_DIR/mmu.o"
compile_kernel "$ROOT_DIR/kernel/sched/scheduler.c" "$KERNEL_BUILD_DIR/scheduler.o"
compile_kernel "$ROOT_DIR/kernel/sched/sched_runqueue.c" "$KERNEL_BUILD_DIR/sched_runqueue.o"
compile_kernel "$ROOT_DIR/kernel/sched/sched_stats.c" "$KERNEL_BUILD_DIR/sched_stats.o"
compile_kernel "$ROOT_DIR/kernel/sched/thread.c" "$KERNEL_BUILD_DIR/thread.o"
if [ "$TARGET_ARCH" = aarch64 ]; then
  compile_kernel "$ROOT_DIR/kernel/sched/context.S" "$KERNEL_BUILD_DIR/context.o"
fi
compile_kernel "$ROOT_DIR/kernel/net/arp.c" "$KERNEL_BUILD_DIR/arp.o"
compile_kernel "$ROOT_DIR/kernel/net/ipv4.c" "$KERNEL_BUILD_DIR/ipv4.o"
compile_kernel "$ROOT_DIR/kernel/net/icmp.c" "$KERNEL_BUILD_DIR/icmp.o"
compile_kernel "$ROOT_DIR/kernel/net/ipv6.c" "$KERNEL_BUILD_DIR/ipv6.o"
compile_kernel "$ROOT_DIR/kernel/net/icmpv6.c" "$KERNEL_BUILD_DIR/icmpv6.o"
compile_kernel "$ROOT_DIR/kernel/net/ndp.c" "$KERNEL_BUILD_DIR/ndp.o"
compile_kernel "$ROOT_DIR/kernel/net/ndp_cache.c" "$KERNEL_BUILD_DIR/ndp_cache.o"
compile_kernel "$ROOT_DIR/kernel/net/ndp_proto.c" "$KERNEL_BUILD_DIR/ndp_proto.o"
compile_kernel "$ROOT_DIR/kernel/net/dhcpv6.c" "$KERNEL_BUILD_DIR/dhcpv6.o"
compile_kernel "$ROOT_DIR/kernel/net/socket_buffer.c" "$KERNEL_BUILD_DIR/socket_buffer.o"
compile_kernel "$ROOT_DIR/kernel/net/routing.c" "$KERNEL_BUILD_DIR/routing.o"
compile_kernel "$ROOT_DIR/kernel/net/dns.c" "$KERNEL_BUILD_DIR/dns.o"
compile_kernel "$ROOT_DIR/kernel/net/dns_resolver.c" "$KERNEL_BUILD_DIR/dns_resolver.o"
compile_kernel "$ROOT_DIR/kernel/net/dns_selftest.c" "$KERNEL_BUILD_DIR/dns_selftest.o"
compile_kernel "$ROOT_DIR/kernel/net/dnssec.c" "$KERNEL_BUILD_DIR/dnssec.o"
compile_kernel "$ROOT_DIR/kernel/net/ntp.c" "$KERNEL_BUILD_DIR/ntp.o"
compile_kernel "$ROOT_DIR/kernel/mm/elf_loader.c" "$KERNEL_BUILD_DIR/elf_loader.o"
compile_kernel "$ROOT_DIR/kernel/lib/string.c" "$KERNEL_BUILD_DIR/string.o"
compile_kernel "$ROOT_DIR/kernel/runtime/bpe_tokenizer.c" "$KERNEL_BUILD_DIR/bpe_tokenizer.o"
compile_kernel "$ROOT_DIR/engine/src/xai_fs.c" "$KERNEL_BUILD_DIR/engine_xai_fs.o"
compile_kernel "$ROOT_DIR/engine/src/xai_fs_writer.c" "$KERNEL_BUILD_DIR/engine_xai_fs_writer.o"
compile_kernel "$ROOT_DIR/engine/src/xai_fs_writer_staging.c" "$KERNEL_BUILD_DIR/engine_xai_fs_writer_staging.o"
compile_kernel "$ROOT_DIR/engine/src/xai_fs_writer_rewrite.c" "$KERNEL_BUILD_DIR/engine_xai_fs_writer_rewrite.o"
compile_kernel "$ROOT_DIR/engine/src/xai_fs_writer_util.c" "$KERNEL_BUILD_DIR/engine_xai_fs_writer_util.o"
compile_kernel "$ROOT_DIR/engine/src/sha256.c" "$KERNEL_BUILD_DIR/engine_sha256.o"
# The accelerated compressor is the one file here that needs SIMD registers,
# and it asks clang for the SHA2 instructions in that function alone rather
# than raising the baseline for anything else. It runs only on a CPU that
# reported the extension; see engine_sha256_dispatch.c.
compile_kernel_simd "$ROOT_DIR/engine/src/sha256_accel.c" "$KERNEL_BUILD_DIR/engine_sha256_accel.o"
compile_kernel "$ROOT_DIR/kernel/runtime/engine_sha256_dispatch.c" "$KERNEL_BUILD_DIR/engine_sha256_dispatch.o"
compile_kernel "$ROOT_DIR/userspace/sshd/ssh_crypto.c" "$KERNEL_BUILD_DIR/kernel_ssh_crypto.o"
compile_kernel "$ROOT_DIR/userspace/sshd/ssh_crypto_symmetric.c" "$KERNEL_BUILD_DIR/kernel_ssh_crypto_symmetric.o"
compile_kernel "$ROOT_DIR/userspace/sshd/ssh_crypto_curve25519.c" "$KERNEL_BUILD_DIR/kernel_ssh_crypto_curve25519.o"
compile_kernel "$ROOT_DIR/userspace/sshd/tweetnacl_subset.c" "$KERNEL_BUILD_DIR/kernel_tweetnacl_subset.o"
KERNEL_RESPONSE_FILE="$KERNEL_BUILD_DIR/objects.rsp"
printf '%s\n' "$KERNEL_OBJECTS" | while IFS= read -r object_path; do
  if [ "$object_path" != "" ]; then
    printf '"%s"\n' "${object_path#  }"
  fi
done > "$KERNEL_RESPONSE_FILE"
KERNEL_BEARSSL="$BUILD_DIR/bearssl/$TARGET_ARCH/libbearssl-xapt.a"
[ -f "$KERNEL_BEARSSL" ] || "$ROOT_DIR/scripts/build-bearssl.sh" "$TARGET_ARCH"
printf '"%s"\n' "$KERNEL_BEARSSL" >> "$KERNEL_RESPONSE_FILE"

"$LD_LLD" \
  -nostdlib \
  $KERNEL_LDFLAGS \
  -T "$ARCH_LINKER" \
  -o "$KERNEL_ELF" \
  @"$KERNEL_RESPONSE_FILE"
