#!/usr/bin/env python3
"""Generate the BearSSL trust anchors xapt validates the updater chain against.

xapt used to pin the updater's exact leaf RSA key. A publicly issued
certificate is renewed every few months with a fresh key, so a leaf pin has to
be re-cut on every renewal or the updater stops working. Anchoring on the
issuing roots instead survives renewal, and the update payload keeps its own
signature, so TLS here only has to establish a trustworthy transport.

The roots come from a trusted local CA store, never from the server being
validated. Regenerate after replacing a PEM in userspace/apps/trust:

    python3 scripts/gen-xapt-trust-anchors.py
"""

import pathlib
import sys

from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    PublicFormat,
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
TRUST_DIR = ROOT / "userspace/apps/trust"
OUTPUT = ROOT / "userspace/apps/xapt_trust_anchors.c"

# BearSSL curve identifiers (br_ec_*), from inc/bearssl_ec.h.
CURVE_IDS = {"secp256r1": 23, "secp384r1": 24, "secp521r1": 25}


def emit_bytes(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    lines.append("};")
    return "\n".join(lines)


def integer_bytes(value):
    return value.to_bytes((value.bit_length() + 7) // 8, "big")


def main():
    pems = sorted(TRUST_DIR.glob("*.pem"))
    if not pems:
        sys.exit(f"no root certificates found in {TRUST_DIR}")

    blocks = []
    entries = []
    for index, pem in enumerate(pems):
        cert = x509.load_pem_x509_certificate(pem.read_bytes())
        public_key = cert.public_key()
        dn = cert.subject.public_bytes()
        blocks.append(f"/* {cert.subject.rfc4514_string()} ({pem.name}) */")
        blocks.append(emit_bytes(f"TA{index}_DN", dn))

        if isinstance(public_key, rsa.RSAPublicKey):
            numbers = public_key.public_numbers()
            blocks.append(emit_bytes(f"TA{index}_N", integer_bytes(numbers.n)))
            blocks.append(emit_bytes(f"TA{index}_E", integer_bytes(numbers.e)))
            key = (
                f"BR_KEYTYPE_RSA,\n"
                f"      {{ .rsa = {{ (unsigned char *)TA{index}_N, sizeof TA{index}_N,\n"
                f"                 (unsigned char *)TA{index}_E, sizeof TA{index}_E }} }}"
            )
        elif isinstance(public_key, ec.EllipticCurvePublicKey):
            curve = public_key.curve.name
            if curve not in CURVE_IDS:
                sys.exit(f"{pem.name}: unsupported curve {curve}")
            point = public_key.public_bytes(
                Encoding.X962, PublicFormat.UncompressedPoint
            )
            blocks.append(emit_bytes(f"TA{index}_Q", point))
            key = (
                f"BR_KEYTYPE_EC,\n"
                f"      {{ .ec = {{ {CURVE_IDS[curve]}, (unsigned char *)TA{index}_Q,\n"
                f"                sizeof TA{index}_Q }} }}"
            )
        else:
            sys.exit(f"{pem.name}: unsupported key type {type(public_key).__name__}")

        entries.append(
            f"    {{ {{ (unsigned char *)TA{index}_DN, sizeof TA{index}_DN }},\n"
            f"      BR_X509_TA_CA,\n"
            f"      {{ {key} }} }},"
        )
        blocks.append("")

    body = "\n".join(blocks)
    table = "\n".join(entries)
    OUTPUT.write_text(
        "/* Generated by scripts/gen-xapt-trust-anchors.py. Do not edit. */\n"
        '#include "xapt_trust_anchors.h"\n\n'
        f"{body}\n"
        "const br_x509_trust_anchor XAPT_TRUST_ANCHORS[] = {\n"
        f"{table}\n"
        "};\n\n"
        "const size_t XAPT_TRUST_ANCHORS_COUNT =\n"
        "    sizeof XAPT_TRUST_ANCHORS / sizeof XAPT_TRUST_ANCHORS[0];\n"
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(pems)} anchors")


if __name__ == "__main__":
    main()
