FROM debian:13-slim

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       grub-efi-arm64-bin \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["grub-mkstandalone"]
