#ifndef XAIOS_USERSPACE_CONTROL_CODES_H
#define XAIOS_USERSPACE_CONTROL_CODES_H

/* Operation codes, payload type codes, maintenance/partition/filesystem
   state codes, status codes, roles, service states and readiness bits for
   the control protocol. Private sub-header of xaios_control.h -- include
   that, not this. The values are wire ABI and keep their exact numbering. */

#define XAIOS_CONTROL_OP_VERSION 1U
#define XAIOS_CONTROL_OP_STATUS 2U
#define XAIOS_CONTROL_OP_HEALTH 3U
#define XAIOS_CONTROL_OP_CAPABILITIES 4U
#define XAIOS_CONTROL_OP_HARDWARE 5U
#define XAIOS_CONTROL_OP_METRICS 6U
#define XAIOS_CONTROL_OP_LOGS 7U
#define XAIOS_CONTROL_OP_CONFIG_SHOW 8U
#define XAIOS_CONTROL_OP_CONFIG_VALIDATE 9U
#define XAIOS_CONTROL_OP_CONFIG_DIFF 10U
#define XAIOS_CONTROL_OP_CONFIG_APPLY 11U
#define XAIOS_CONTROL_OP_AUTH_KEY_LIST 12U
#define XAIOS_CONTROL_OP_AUTH_KEY_ADD 13U
#define XAIOS_CONTROL_OP_AUTH_KEY_REMOVE 14U
#define XAIOS_CONTROL_OP_AUTH_HOST_KEY_ROTATE 15U
#define XAIOS_CONTROL_OP_AUDIT_SHOW 16U
#define XAIOS_CONTROL_OP_MODEL_VERIFY 17U
#define XAIOS_CONTROL_OP_MODEL_ACTIVATE 18U
#define XAIOS_CONTROL_OP_STORAGE_DEVICE_LIST 19U
#define XAIOS_CONTROL_OP_STORAGE_DEVICE_SHOW 20U
#define XAIOS_CONTROL_OP_STORAGE_FILESYSTEM_LIST 21U
#define XAIOS_CONTROL_OP_STORAGE_FILESYSTEM_SHOW 22U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_LIST 23U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_VERIFY 24U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_PLAN_CREATE 25U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_CREATE 26U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_PLAN_DELETE 27U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_DELETE 28U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_PLAN_RESIZE 29U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_RESIZE 30U
#define XAIOS_CONTROL_OP_STORAGE_PARTITION_REPAIR 31U
#define XAIOS_CONTROL_OP_STORAGE_FORMAT_PLAN 32U
#define XAIOS_CONTROL_OP_STORAGE_FORMAT 33U
#define XAIOS_CONTROL_OP_STORAGE_MOUNT 34U
#define XAIOS_CONTROL_OP_STORAGE_UNMOUNT 35U
#define XAIOS_CONTROL_OP_STORAGE_FSCK 36U
#define XAIOS_CONTROL_OP_STORAGE_FS_REPAIR 37U
#define XAIOS_CONTROL_OP_STORAGE_FS_RESIZE_PLAN 38U
#define XAIOS_CONTROL_OP_STORAGE_FS_RESIZE 39U
#define XAIOS_CONTROL_OP_MODEL_REGISTER 40U
#define XAIOS_CONTROL_OP_STORAGE_SCRUB_START 41U
#define XAIOS_CONTROL_OP_STORAGE_SCRUB_STATUS 42U
#define XAIOS_CONTROL_OP_STORAGE_SCRUB_PAUSE 43U
#define XAIOS_CONTROL_OP_STORAGE_SCRUB_RESUME 44U
#define XAIOS_CONTROL_OP_STORAGE_SCRUB_CANCEL 45U
#define XAIOS_CONTROL_OP_STORAGE_TRIM_START 46U
#define XAIOS_CONTROL_OP_STORAGE_TRIM_STATUS 47U
#define XAIOS_CONTROL_OP_STORAGE_TRIM_CANCEL 48U
#define XAIOS_CONTROL_OP_MODEL_CLEANUP 49U
#define XAIOS_CONTROL_OP_APP_ACTIVATE 50U
#define XAIOS_CONTROL_OP_APP_REMOVE 51U
#define XAIOS_CONTROL_OP_APP_ROLLBACK 52U
#define XAIOS_CONTROL_OP_CATALOG_ACTIVATE 53U
#define XAIOS_CONTROL_OP_SYSTEM_UPDATE_BEGIN 54U
#define XAIOS_CONTROL_OP_SYSTEM_UPDATE_CHUNK 55U
#define XAIOS_CONTROL_OP_SYSTEM_UPDATE_COMMIT 56U
#define XAIOS_CONTROL_OP_SYSTEM_UPDATE_ABORT 57U
#define XAIOS_CONTROL_OP_RUNTIME_SNAPSHOT 58U
#define XAIOS_CONTROL_OP_STORAGE_REPAIR_FROM_REPLICA 59U
/* Partition a disk, format its EFI System Partition and copy this machine's
   own boot files onto it. Destroys the target, so it carries the same
   confirmation, actor and audit requirements as a partition mutation. */
#define XAIOS_CONTROL_OP_STORAGE_INSTALL 60U

#define XAIOS_CONTROL_PAYLOAD_NONE 0U
#define XAIOS_CONTROL_PAYLOAD_VERSION 1U
#define XAIOS_CONTROL_PAYLOAD_STATUS 2U
#define XAIOS_CONTROL_PAYLOAD_HEALTH 3U
#define XAIOS_CONTROL_PAYLOAD_CAPABILITIES 4U
#define XAIOS_CONTROL_PAYLOAD_HARDWARE 5U
#define XAIOS_CONTROL_PAYLOAD_METRICS 6U
#define XAIOS_CONTROL_PAYLOAD_LOG_REQUEST 7U
#define XAIOS_CONTROL_PAYLOAD_LOGS 8U
#define XAIOS_CONTROL_PAYLOAD_PATH_REQUEST 9U
#define XAIOS_CONTROL_PAYLOAD_MUTATION_REQUEST 10U
#define XAIOS_CONTROL_PAYLOAD_AUDIT_REQUEST 11U
#define XAIOS_CONTROL_PAYLOAD_CONFIG 12U
#define XAIOS_CONTROL_PAYLOAD_AUTH_KEYS 13U
#define XAIOS_CONTROL_PAYLOAD_MUTATION 14U
#define XAIOS_CONTROL_PAYLOAD_AUDIT 15U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_DEVICES 16U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_FILESYSTEMS 17U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_PARTITION_REQUEST 18U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_PARTITIONS 19U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_PARTITION_PLAN 20U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_VOLUME_REQUEST 21U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_VOLUME_REPORT 22U
#define XAIOS_CONTROL_PAYLOAD_MODEL_REGISTER_REQUEST 23U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_SCRUB_REPORT 24U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_TRIM_REQUEST 25U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_TRIM_REPORT 26U
#define XAIOS_CONTROL_PAYLOAD_MODEL_CLEANUP_REPORT 27U
#define XAIOS_CONTROL_PAYLOAD_APP_REQUEST 28U
#define XAIOS_CONTROL_PAYLOAD_SYSTEM_UPDATE_BEGIN 29U
#define XAIOS_CONTROL_PAYLOAD_SYSTEM_UPDATE_CHUNK 30U
#define XAIOS_CONTROL_PAYLOAD_RUNTIME_SNAPSHOT_REQUEST 31U
#define XAIOS_CONTROL_PAYLOAD_RUNTIME_SNAPSHOT 32U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_REPLICA_REPAIR_REQUEST 33U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_INSTALL_REQUEST 34U
#define XAIOS_CONTROL_PAYLOAD_STORAGE_INSTALL_RESULT 35U

#define XAIOS_MODEL_MAINTENANCE_IDLE 0U
#define XAIOS_MODEL_MAINTENANCE_RUNNING 1U
#define XAIOS_MODEL_MAINTENANCE_PAUSED 2U
#define XAIOS_MODEL_MAINTENANCE_COMPLETE 3U
#define XAIOS_MODEL_MAINTENANCE_CANCELLED 4U
#define XAIOS_MODEL_MAINTENANCE_FAILED 5U

#define XAIOS_STORAGE_PARTITION_STATE 1U
#define XAIOS_STORAGE_PARTITION_MODEL 2U
#define XAIOS_STORAGE_PARTITION_RECOVERY 3U
/* The EFI System Partition. Firmware looks for one specific type GUID, so a
   partition XAIOS creates for its own loader carries the standard one. */
#define XAIOS_STORAGE_PARTITION_ESP 4U

#define XAIOS_XAI_FS_CHECK_UNKNOWN 0U
#define XAIOS_XAI_FS_CHECK_CLEAN 1U
#define XAIOS_XAI_FS_CHECK_REPAIRABLE 2U
#define XAIOS_XAI_FS_CHECK_CORRUPT_UNREPAIRABLE 3U
#define XAIOS_XAI_FS_CHECK_REPAIRED 4U

#define XAIOS_CONTROL_STATUS_OK 0U
#define XAIOS_CONTROL_STATUS_INVALID_REQUEST 1U
#define XAIOS_CONTROL_STATUS_UNSUPPORTED_VERSION 2U
#define XAIOS_CONTROL_STATUS_UNKNOWN_OPERATION 3U
#define XAIOS_CONTROL_STATUS_DENIED 4U
#define XAIOS_CONTROL_STATUS_BUFFER_TOO_SMALL 5U
#define XAIOS_CONTROL_STATUS_TIMEOUT 6U
#define XAIOS_CONTROL_STATUS_INTERNAL 7U
#define XAIOS_CONTROL_STATUS_UNKNOWN_NODE 8U
#define XAIOS_CONTROL_STATUS_NOT_FOUND 9U
#define XAIOS_CONTROL_STATUS_REPLAYED 10U
#define XAIOS_CONTROL_STATUS_CONFLICT 11U

#define XAIOS_CONTROL_ROLE_NONE 0U
#define XAIOS_CONTROL_ROLE_OBSERVER 1U
#define XAIOS_CONTROL_ROLE_OPERATOR 2U
#define XAIOS_CONTROL_ROLE_ADMIN 3U

#define XAIOS_CONTROL_STATE_UNKNOWN 0U
#define XAIOS_CONTROL_STATE_STOPPED 1U
#define XAIOS_CONTROL_STATE_RUNNING 2U
#define XAIOS_CONTROL_STATE_READY 3U
#define XAIOS_CONTROL_STATE_DEGRADED 4U
#define XAIOS_CONTROL_STATE_FATAL 5U
#define XAIOS_CONTROL_STATE_UNSUPPORTED 6U
#define XAIOS_CONTROL_STATE_INTERFACE_ONLY 7U
#define XAIOS_CONTROL_STATE_FIXTURE_ONLY 8U
#define XAIOS_CONTROL_STATE_AVAILABLE 9U

#define XAIOS_CONTROL_READINESS_SSH 1ULL
#define XAIOS_CONTROL_READINESS_NETWORK 2ULL
#define XAIOS_CONTROL_READINESS_STORAGE 4ULL
#define XAIOS_CONTROL_READINESS_MODEL 8ULL
#define XAIOS_CONTROL_READINESS_INFERENCE 16ULL
#define XAIOS_CONTROL_READINESS_CLUSTER 32ULL

#endif
